opt: !!python/object:argparse.Namespace
  Dsteps: 3
  Gsteps: 3
  ImgGen: []
  alpha: 100
  alpha_layer_type: all-ones
  batch_size: 256
  beta1: 0.5
  d1_input_name: lvl_1-3.txt
  d2_input_name: lvl_1-3.txt
  debug: false
  device: !!python/object/apply:torch.device
  - cuda
  - 0
  emb_dimension: 3
  epochs: 30
  game: mario
  gamma: 0.1
  initial_lr: 0.001
  input_dir: input
  input_name: lvl_1-1.txt
  ker_size: 3
  lambda_grad: 0.1
  lr_d: 0.0005
  lr_g: 0.0005
  manualSeed: 1753
  nc_current: 12
  neighbor_radius: 1
  netD1: ''
  netD2: ''
  netG: ''
  nfc: 64
  niter: 4000
  noise_amp: 1.0
  noise_update: 0.1
  not_cuda: 0
  num_layer: 3
  num_scales: 3
  out: output
  out_: output/lvl_1-3/
  outf: '0'
  output_dir: /Users/dgilles2/Github/TOAD-GAN/./mario/block2vec/../../output/block2vec
  pad_with_noise: false
  scales:
  - 0.88
  - 0.75
  - 0.5
  seed_road: null
  stop_scale: 3
  token_insert: -2
  token_list:
  - '!'
  - '#'
  - '-'
  - '1'
  - '@'
  - C
  - S
  - U
  - X
  - g
  - k
  - t
